ClassImageFunctions Class Reference
#include <ImageFunctions.h>
Public Member Functions
ClassImageFunctions ()
~ClassImageFunctions ()
char IF_Threshold (IplImage *src, IplImage *dst, unsigned char Limit)
char IF_Threshold (IplImage *src, IplImage *dst, unsigned int Limit)
char SetMaxLimit (int val)
Private Attributes
unsigned char MaxLimit
Constructor & Destructor Documentation
ClassImageFunctions::ClassImageFunctions ()
This is the constructor
Returns:
Definition at line 25 of file ImageFunctions.cpp.
References MaxLimit.
26 {
27         MaxLimit = 255;
28 }
ClassImageFunctions::~ClassImageFunctions () [inline]
Definition at line 38 of file ImageFunctions.h.
38 {}; 
Member Function Documentation
char ClassImageFunctions::IF_Threshold (IplImage * src, IplImage * dst, unsigned int Limit)
Definition at line 38 of file ImageFunctions.cpp.
References IF_Threshold().
39 {
40         return IF_Threshold(src,dst,(unsigned char) Limit);
41 };
char ClassImageFunctions::IF_Threshold (IplImage * src, IplImage * dst, unsigned char Limit)
This funtion threshold src image and gives the result in dst image
Parameters:
src ->source image
dst ->destination image
Limit ->threshol limit
Returns:
Definition at line 30 of file ImageFunctions.cpp.
References MaxLimit.
Referenced by IF_Threshold(), and main().
31 {
32         if(! src || ! dst ) return -1;
33         cvThreshold(src,dst,Limit,MaxLimit,CV_THRESH_BINARY);
34         return 1;
35 }       
char ClassImageFunctions::SetMaxLimit (int val)
ola gosto muito de ti
Parameters:
val
Returns:
Definition at line 44 of file ImageFunctions.cpp.
References MaxLimit.
Referenced by main().
45 {
46 
47         if(val >=0 && val<256)
48         {       
49                 MaxLimit = val;
50                 return 1;
51         }
52         else
53         {       
54                 return -1;
55         }
56 
57 }
Member Data Documentation
unsigned char ClassImageFunctions::MaxLimit [private]
Definition at line 63 of file ImageFunctions.h.
Referenced by ClassImageFunctions(), IF_Threshold(), and SetMaxLimit().
The documentation for this class was generated from the following files:
/home/mike/progs/ATLASIV/imagetoolbox/src/ImageFunctions.h
/home/mike/progs/ATLASIV/imagetoolbox/src/ImageFunctions.cpp